'use client'

import { useEffect, useState } from 'react'
import { supabaseBrowser } from '@/lib/supabase-browser'
import type { Task } from '@/types'

const priorityLabel: Record<string, string> = { urgent: '🔴 Urgent', high: '🟠 High', medium: '🟡 Medium', low: '🔵 Low' }
const typeLabel: Record<string, string> = { task: 'Task', event: 'Event', reminder: 'Reminder' }

export default function PrintPage() {
  const [tasks, setTasks] = useState<Task[]>([])
  const [loading, setLoading] = useState(true)
  const [user, setUser] = useState<string>('')

  useEffect(() => {
    supabaseBrowser.auth.getUser().then(({ data }) => {
      if (!data.user) return
      setUser(data.user.email ?? '')
      fetch('/api/tasks')
        .then(r => r.json())
        .then((d: { tasks?: Task[] } | Task[]) => {
          const arr = Array.isArray(d) ? d : (d as { tasks?: Task[] }).tasks ?? []
          setTasks(arr)
        })
        .finally(() => setLoading(false))
    })
  }, [])

  useEffect(() => {
    if (!loading && tasks.length > 0) {
      setTimeout(() => window.print(), 400)
    }
  }, [loading, tasks])

  const pending = tasks.filter(t => t.status === 'pending')
  const done    = tasks.filter(t => t.status === 'done')

  if (loading) {
    return <div className="flex items-center justify-center py-24 text-slate-400">Preparing PDF…</div>
  }

  return (
    <>
      {/* Print styles */}
      <style>{`
        @media print {
          body { background: white !important; color: black !important; }
          .no-print { display: none !important; }
          .print-page { padding: 0 !important; }
        }
        @media screen {
          body { background: #06060f; }
        }
      `}</style>

      <div className="print-page max-w-3xl mx-auto px-8 py-10 space-y-8">
        {/* No-print bar */}
        <div className="no-print flex items-center justify-between mb-6 glass rounded-2xl border border-white/10 px-5 py-3">
          <p className="text-sm text-slate-400">Preview — click Print or wait for the dialog</p>
          <div className="flex items-center gap-3">
            <button onClick={() => window.print()} className="rounded-xl bg-gradient-to-r from-violet-600 to-cyan-500 px-4 py-2 text-sm font-bold text-white">
              🖨 Print / Save PDF
            </button>
            <button onClick={() => window.close()} className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-slate-400 hover:text-white">
              ✕ Close
            </button>
          </div>
        </div>

        {/* Header */}
        <div className="border-b border-gray-200 pb-6 space-y-1">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl font-black text-white print:text-black">GlanceFlow — Task List</h1>
            <span className="text-xs text-slate-400 print:text-gray-500">
              {new Date().toLocaleDateString('en', { day: 'numeric', month: 'long', year: 'numeric' })}
            </span>
          </div>
          <p className="text-sm text-slate-500 print:text-gray-500">{user} · {tasks.length} tasks total</p>
        </div>

        {/* Pending tasks */}
        {pending.length > 0 && (
          <div className="space-y-3">
            <h2 className="text-sm font-black uppercase tracking-widest text-violet-400 print:text-gray-700">
              Pending ({pending.length})
            </h2>
            <div className="space-y-2">
              {pending.map(t => <TaskRow key={t.id} task={t} />)}
            </div>
          </div>
        )}

        {/* Done tasks */}
        {done.length > 0 && (
          <div className="space-y-3">
            <h2 className="text-sm font-black uppercase tracking-widest text-emerald-400 print:text-gray-700">
              Completed ({done.length})
            </h2>
            <div className="space-y-2 opacity-60">
              {done.map(t => <TaskRow key={t.id} task={t} />)}
            </div>
          </div>
        )}

        <div className="pt-6 border-t border-gray-200 text-center text-xs text-slate-500 print:text-gray-400">
          Generated by GlanceFlow · glanceflow.app
        </div>
      </div>
    </>
  )
}

function TaskRow({ task }: { task: Task }) {
  const subtasksDone = (task.subtasks ?? []).filter(s => s.done).length
  const subtasksTotal = (task.subtasks ?? []).length

  return (
    <div className="flex items-start gap-3 rounded-xl border border-white/8 print:border-gray-200 px-4 py-3">
      <div className={`shrink-0 mt-0.5 h-4 w-4 rounded border-2 ${task.status === 'done' ? 'border-emerald-500 bg-emerald-500/20 print:bg-green-100 print:border-green-500' : 'border-white/30 print:border-gray-400'}`}>
        {task.status === 'done' && <svg className="h-3 w-3 text-emerald-400 print:text-green-600 m-auto mt-0.5" fill="none" viewBox="0 0 10 10" stroke="currentColor" strokeWidth={2}><path d="M1.5 5l2.5 2.5 4.5-5"/></svg>}
      </div>
      <div className="flex-1 min-w-0 space-y-0.5">
        <p className={`text-sm font-semibold text-white print:text-black ${task.status === 'done' ? 'line-through text-slate-500 print:text-gray-400' : ''}`}>
          {task.title}
        </p>
        <div className="flex flex-wrap items-center gap-3 text-[11px] text-slate-500 print:text-gray-500">
          <span>{typeLabel[task.type]}</span>
          {task.priority && <span>{priorityLabel[task.priority]}</span>}
          {task.date && <span>📅 {task.date}</span>}
          {task.time && <span>🕐 {task.time}</span>}
          {subtasksTotal > 0 && <span>☑ {subtasksDone}/{subtasksTotal} subtasks</span>}
        </div>
      </div>
    </div>
  )
}
