'use client'

import { createContext, useContext, useEffect, useState } from 'react'

export type Lang = 'en' | 'it' | 'es' | 'fr' | 'de'

interface LanguageContextValue {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: string) => string
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.pricing': 'Pricing',
    'nav.profile': 'Profile',
    'nav.signout': 'Sign out',
    'nav.signin': 'Sign in',
    'nav.tools': 'Tools',
    'nav.upgrade': '+ Upgrade',

    // Login
    'login.welcome': 'Welcome back',
    'login.create': 'Create your account',
    'login.subtitle.login': 'Sign in to GlanceFlow',
    'login.subtitle.signup': 'Free — 3 tasks/day',
    'login.google': 'Continue with Google',
    'login.google.loading': 'Redirecting…',
    'login.or': 'or',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.password.placeholder': 'Min 6 characters',
    'login.submit.login': 'Sign in',
    'login.submit.signup': 'Create account',
    'login.loading': 'Loading…',
    'login.noAccount': "Don't have an account?",
    'login.hasAccount': 'Already have an account?',
    'login.signupFree': 'Sign up free',
    'login.check.title': 'Check your email',
    'login.check.desc': 'We sent a confirmation link to',
    'login.check.back': 'Back to sign in',

    // Pricing
    'pricing.badge': 'Simple pricing',
    'pricing.title': 'Choose your',
    'pricing.title.highlight': 'plan',
    'pricing.subtitle': 'Start free, upgrade when you need more. No hidden fees.',
    'pricing.free.label': 'Free',
    'pricing.free.price': '€0',
    'pricing.free.period': '/forever',
    'pricing.free.tagline': 'Perfect to get started',
    'pricing.free.cta': 'Get started free',
    'pricing.premium.label': 'Premium',
    'pricing.premium.price': '€6.99',
    'pricing.premium.period': '/month',
    'pricing.premium.tagline': 'For daily power users',
    'pricing.premium.cta': 'Start Premium',
    'pricing.premium.cta.loading': 'Redirecting…',
    'pricing.pro.label': 'Pro',
    'pricing.pro.badge': '✦ Most Powerful',
    'pricing.pro.price': '€20',
    'pricing.pro.period': '/month',
    'pricing.pro.tagline': 'Full power, no limits',
    'pricing.pro.cta': 'Start Pro',
    'pricing.pro.cta.loading': 'Redirecting…',
    'pricing.unlock.title': 'What you unlock with Pro',
    'pricing.unlock.subtitle': 'Everything Premium has, plus the tools serious users need',
    'pricing.trust.stripe': '🔒 Secure via Stripe',
    'pricing.trust.cancel': '↩ Cancel anytime',
    'pricing.trust.instant': '⚡ Instant activation',
    'pricing.trust.vat': '🇪🇺 VAT included',
    'pricing.faq.title': 'FAQ',
    'pricing.faq.q1': 'Can I cancel anytime?',
    'pricing.faq.a1': 'Yes, cancel with one click from your Stripe billing portal. No questions asked.',
    'pricing.faq.q2': 'What is the difference between Premium and Pro?',
    'pricing.faq.a2': 'Premium covers unlimited screenshots and all core AI features. Pro adds webhooks, calendar view, priority AI processing, on-demand summaries and advanced analytics.',
    'pricing.faq.q3': 'What counts as a screenshot?',
    'pricing.faq.a3': 'Every image you upload and process with AI counts as one screenshot.',
    'pricing.faq.q4': 'Do unused free screenshots roll over?',
    'pricing.faq.a4': 'No, the free limit resets every day at midnight.',
    'pricing.faq.q5': 'What is the AI Smart Summary?',
    'pricing.faq.a5': 'An AI-generated email that summarises your pending tasks, highlights priorities and gives you a motivating overview.',
    'pricing.faq.q6': 'Is my data safe?',
    'pricing.faq.a6': 'Yes. Tasks are stored in your private Supabase database. Screenshots are never stored.',

    // Home hero
    'home.badge': 'AI-Powered Productivity',
    'home.hero.title1': 'Turn any screenshot into',
    'home.hero.title2': 'organized tasks',
    'home.hero.title3': 'in seconds',
    'home.hero.subtitle': 'Upload a screenshot. GlanceFlow\'s AI extracts tasks, priorities, and deadlines automatically. Free to start.',
    'home.hero.cta': 'Start free — no card needed',
    'home.hero.demo': 'See how it works',
    'home.hero.free': '✓ Free forever',
    'home.hero.noCard': '✓ No credit card',
    'home.hero.ai': '✓ AI-powered',
    'home.how.badge': 'How it works',
    'home.how.title': 'From screenshot to tasks',
    'home.how.title2': 'in 3 steps',
    'home.how.step1.title': 'Upload',
    'home.how.step1.desc': 'Take a screenshot of anything — emails, chats, notes, web pages.',
    'home.how.step2.title': 'AI Extracts',
    'home.how.step2.desc': 'Our AI reads the screenshot and pulls out every task, deadline and priority.',
    'home.how.step3.title': 'Get Organized',
    'home.how.step3.desc': 'Tasks appear in your dashboard, sorted by priority and ready to act on.',
    'home.cta.title': 'Ready to get organized?',
    'home.cta.subtitle': 'Join thousands of users who turned chaos into clarity.',
    'home.cta.btn': 'Start for free',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.noTasks': 'No tasks yet — upload a screenshot to get started.',
    'dashboard.upload': 'Upload a screenshot →',
    'dashboard.search': 'Search tasks… (/)',
    'dashboard.all': 'All',
    'dashboard.pending': 'Pending',
    'dashboard.done': 'Done',
    'dashboard.task': 'Task',
    'dashboard.event': 'Event',
    'dashboard.reminder': 'Reminder',
    'dashboard.markDone': '✓ Mark as Done',
    'dashboard.tasks': 'tasks',
    'dashboard.tasksDone': 'done',

    // Profile
    'profile.title': 'Profile',
    'profile.email': 'Email',
    'profile.plan': 'Plan',
    'profile.plan.free': 'Free',
    'profile.plan.premium': '✦ Premium',
    'profile.plan.pro': '✦ Pro',
    'profile.usage': 'Usage today',
    'profile.language': 'Language',
    'profile.changePassword': 'Change password',
    'profile.changePassword.desc': 'We will send a reset link to your email.',
    'profile.changePassword.btn': 'Send reset link',
    'profile.changePassword.sent': 'Email sent! Check your inbox.',
    'profile.member': 'Member since',
    'profile.upgrade': 'Upgrade to Premium →',
    'profile.manageSubscription': 'Manage subscription →',

    // Footer
    'footer.product': 'Product',
    'footer.legal': 'Legal',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact',
    'footer.rights': '© 2026 GlanceFlow. All rights reserved.',
    'footer.made': 'Made with ♥ for productivity',
  },

  it: {
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.pricing': 'Prezzi',
    'nav.profile': 'Profilo',
    'nav.signout': 'Esci',
    'nav.signin': 'Accedi',
    'nav.tools': 'Strumenti',
    'nav.upgrade': '+ Upgrade',

    'login.welcome': 'Bentornato',
    'login.create': 'Crea il tuo account',
    'login.subtitle.login': 'Accedi a GlanceFlow',
    'login.subtitle.signup': 'Gratuito — 3 task al giorno',
    'login.google': 'Continua con Google',
    'login.google.loading': 'Reindirizzamento…',
    'login.or': 'oppure',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.password.placeholder': 'Min 6 caratteri',
    'login.submit.login': 'Accedi',
    'login.submit.signup': 'Crea account',
    'login.loading': 'Caricamento…',
    'login.noAccount': 'Non hai un account?',
    'login.hasAccount': 'Hai già un account?',
    'login.signupFree': 'Registrati gratis',
    'login.check.title': 'Controlla la tua email',
    'login.check.desc': 'Abbiamo inviato un link di conferma a',
    'login.check.back': 'Torna al login',

    'pricing.badge': 'Prezzi semplici',
    'pricing.title': 'Scegli il tuo',
    'pricing.title.highlight': 'piano',
    'pricing.subtitle': 'Inizia gratis, passa a un piano superiore quando ne hai bisogno. Nessun costo nascosto.',
    'pricing.free.label': 'Gratuito',
    'pricing.free.price': '€0',
    'pricing.free.period': '/sempre',
    'pricing.free.tagline': 'Perfetto per iniziare',
    'pricing.free.cta': 'Inizia gratis',
    'pricing.premium.label': 'Premium',
    'pricing.premium.price': '€6,99',
    'pricing.premium.period': '/mese',
    'pricing.premium.tagline': 'Per gli utenti quotidiani',
    'pricing.premium.cta': 'Inizia Premium',
    'pricing.premium.cta.loading': 'Reindirizzamento…',
    'pricing.pro.label': 'Pro',
    'pricing.pro.badge': '✦ Più Potente',
    'pricing.pro.price': '€20',
    'pricing.pro.period': '/mese',
    'pricing.pro.tagline': 'Tutta la potenza, nessun limite',
    'pricing.pro.cta': 'Inizia Pro',
    'pricing.pro.cta.loading': 'Reindirizzamento…',
    'pricing.unlock.title': 'Cosa sblocchi con Pro',
    'pricing.unlock.subtitle': 'Tutto di Premium, più gli strumenti per gli utenti seri',
    'pricing.trust.stripe': '🔒 Sicuro via Stripe',
    'pricing.trust.cancel': '↩ Cancella quando vuoi',
    'pricing.trust.instant': '⚡ Attivazione immediata',
    'pricing.trust.vat': '🇪🇺 IVA inclusa',
    'pricing.faq.title': 'FAQ',
    'pricing.faq.q1': 'Posso cancellare in qualsiasi momento?',
    'pricing.faq.a1': 'Sì, cancella con un clic dal portale di fatturazione Stripe. Nessuna domanda.',
    'pricing.faq.q2': 'Qual è la differenza tra Premium e Pro?',
    'pricing.faq.a2': 'Premium copre screenshot illimitati e tutte le funzioni AI. Pro aggiunge webhook, vista calendario, elaborazione AI prioritaria, riepiloghi on-demand e analisi avanzate.',
    'pricing.faq.q3': 'Cosa conta come screenshot?',
    'pricing.faq.a3': 'Ogni immagine che carichi ed elabori con l\'AI conta come uno screenshot.',
    'pricing.faq.q4': 'Gli screenshot gratuiti inutilizzati si accumulano?',
    'pricing.faq.a4': 'No, il limite gratuito si azzera ogni giorno a mezzanotte.',
    'pricing.faq.q5': 'Cos\'è l\'AI Smart Summary?',
    'pricing.faq.a5': 'Un\'email generata dall\'AI che riepiloga i tuoi task in sospeso, evidenzia le priorità e ti dà una panoramica motivante.',
    'pricing.faq.q6': 'I miei dati sono al sicuro?',
    'pricing.faq.a6': 'Sì. I task sono memorizzati nel tuo database Supabase privato. Gli screenshot non vengono mai salvati.',

    'home.badge': 'Produttività con AI',
    'home.hero.title1': 'Trasforma qualsiasi screenshot in',
    'home.hero.title2': 'task organizzati',
    'home.hero.title3': 'in secondi',
    'home.hero.subtitle': 'Carica uno screenshot. L\'AI di GlanceFlow estrae task, priorità e scadenze automaticamente. Gratis per iniziare.',
    'home.hero.cta': 'Inizia gratis — nessuna carta',
    'home.hero.demo': 'Scopri come funziona',
    'home.hero.free': '✓ Gratis per sempre',
    'home.hero.noCard': '✓ Nessuna carta di credito',
    'home.hero.ai': '✓ Powered by AI',
    'home.how.badge': 'Come funziona',
    'home.how.title': 'Dallo screenshot ai task',
    'home.how.title2': 'in 3 passi',
    'home.how.step1.title': 'Carica',
    'home.how.step1.desc': 'Fai uno screenshot di qualsiasi cosa — email, chat, note, pagine web.',
    'home.how.step2.title': 'L\'AI Estrae',
    'home.how.step2.desc': 'La nostra AI legge lo screenshot ed estrae ogni task, scadenza e priorità.',
    'home.how.step3.title': 'Organizzati',
    'home.how.step3.desc': 'I task appaiono nella tua dashboard, ordinati per priorità e pronti per l\'azione.',
    'home.cta.title': 'Pronto ad organizzarti?',
    'home.cta.subtitle': 'Unisciti a migliaia di utenti che hanno trasformato il caos in chiarezza.',
    'home.cta.btn': 'Inizia gratis',

    'dashboard.title': 'Dashboard',
    'dashboard.noTasks': 'Nessun task ancora — carica uno screenshot per iniziare.',
    'dashboard.upload': 'Carica uno screenshot →',
    'dashboard.search': 'Cerca task… (/)',
    'dashboard.all': 'Tutti',
    'dashboard.pending': 'In corso',
    'dashboard.done': 'Completati',
    'dashboard.task': 'Task',
    'dashboard.event': 'Evento',
    'dashboard.reminder': 'Promemoria',
    'dashboard.markDone': '✓ Segna come fatto',
    'dashboard.tasks': 'task',
    'dashboard.tasksDone': 'completati',

    'profile.title': 'Profilo',
    'profile.email': 'Email',
    'profile.plan': 'Piano',
    'profile.plan.free': 'Gratuito',
    'profile.plan.premium': '✦ Premium',
    'profile.plan.pro': '✦ Pro',
    'profile.usage': 'Utilizzo oggi',
    'profile.language': 'Lingua',
    'profile.changePassword': 'Cambia password',
    'profile.changePassword.desc': 'Ti invieremo un link di reset alla tua email.',
    'profile.changePassword.btn': 'Invia link di reset',
    'profile.changePassword.sent': 'Email inviata! Controlla la tua casella.',
    'profile.member': 'Membro da',
    'profile.upgrade': 'Passa a Premium →',
    'profile.manageSubscription': 'Gestisci abbonamento →',

    'footer.product': 'Prodotto',
    'footer.legal': 'Legale',
    'footer.terms': 'Termini di Servizio',
    'footer.contact': 'Contatti',
    'footer.rights': '© 2026 GlanceFlow. Tutti i diritti riservati.',
    'footer.made': 'Fatto con ♥ per la produttività',
  },

  es: {
    'nav.home': 'Inicio',
    'nav.dashboard': 'Panel',
    'nav.pricing': 'Precios',
    'nav.profile': 'Perfil',
    'nav.signout': 'Cerrar sesión',
    'nav.signin': 'Iniciar sesión',
    'nav.tools': 'Herramientas',
    'nav.upgrade': '+ Mejorar',

    'login.welcome': 'Bienvenido de nuevo',
    'login.create': 'Crea tu cuenta',
    'login.subtitle.login': 'Inicia sesión en GlanceFlow',
    'login.subtitle.signup': 'Gratis — 3 tareas al día',
    'login.google': 'Continuar con Google',
    'login.google.loading': 'Redirigiendo…',
    'login.or': 'o',
    'login.email': 'Correo',
    'login.password': 'Contraseña',
    'login.password.placeholder': 'Mín 6 caracteres',
    'login.submit.login': 'Iniciar sesión',
    'login.submit.signup': 'Crear cuenta',
    'login.loading': 'Cargando…',
    'login.noAccount': '¿No tienes cuenta?',
    'login.hasAccount': '¿Ya tienes cuenta?',
    'login.signupFree': 'Regístrate gratis',
    'login.check.title': 'Revisa tu correo',
    'login.check.desc': 'Enviamos un enlace de confirmación a',
    'login.check.back': 'Volver al inicio de sesión',

    'pricing.badge': 'Precios simples',
    'pricing.title': 'Elige tu',
    'pricing.title.highlight': 'plan',
    'pricing.subtitle': 'Empieza gratis, mejora cuando necesites más. Sin cargos ocultos.',
    'pricing.free.label': 'Gratis',
    'pricing.free.price': '€0',
    'pricing.free.period': '/siempre',
    'pricing.free.tagline': 'Perfecto para empezar',
    'pricing.free.cta': 'Empezar gratis',
    'pricing.premium.label': 'Premium',
    'pricing.premium.price': '€6,99',
    'pricing.premium.period': '/mes',
    'pricing.premium.tagline': 'Para usuarios diarios',
    'pricing.premium.cta': 'Empezar Premium',
    'pricing.premium.cta.loading': 'Redirigiendo…',
    'pricing.pro.label': 'Pro',
    'pricing.pro.badge': '✦ Más Potente',
    'pricing.pro.price': '€20',
    'pricing.pro.period': '/mes',
    'pricing.pro.tagline': 'Todo el poder, sin límites',
    'pricing.pro.cta': 'Empezar Pro',
    'pricing.pro.cta.loading': 'Redirigiendo…',
    'pricing.unlock.title': 'Qué desbloqueas con Pro',
    'pricing.unlock.subtitle': 'Todo lo de Premium, más las herramientas para usuarios serios',
    'pricing.trust.stripe': '🔒 Seguro via Stripe',
    'pricing.trust.cancel': '↩ Cancela cuando quieras',
    'pricing.trust.instant': '⚡ Activación inmediata',
    'pricing.trust.vat': '🇪🇺 IVA incluido',
    'pricing.faq.title': 'Preguntas frecuentes',
    'pricing.faq.q1': '¿Puedo cancelar en cualquier momento?',
    'pricing.faq.a1': 'Sí, cancela con un clic desde tu portal de facturación de Stripe. Sin preguntas.',
    'pricing.faq.q2': '¿Cuál es la diferencia entre Premium y Pro?',
    'pricing.faq.a2': 'Premium cubre capturas ilimitadas y todas las funciones AI. Pro añade webhooks, vista de calendario, procesamiento AI prioritario, resúmenes bajo demanda y análisis avanzados.',
    'pricing.faq.q3': '¿Qué cuenta como captura de pantalla?',
    'pricing.faq.a3': 'Cada imagen que subas y proceses con AI cuenta como una captura.',
    'pricing.faq.q4': '¿Las capturas gratuitas no utilizadas se acumulan?',
    'pricing.faq.a4': 'No, el límite gratuito se restablece cada día a medianoche.',
    'pricing.faq.q5': '¿Qué es el AI Smart Summary?',
    'pricing.faq.a5': 'Un correo generado por IA que resume tus tareas pendientes, resalta prioridades y te da una visión motivadora.',
    'pricing.faq.q6': '¿Están seguros mis datos?',
    'pricing.faq.a6': 'Sí. Las tareas se almacenan en tu base de datos privada de Supabase. Las capturas nunca se guardan.',

    'home.badge': 'Productividad con IA',
    'home.hero.title1': 'Convierte cualquier captura en',
    'home.hero.title2': 'tareas organizadas',
    'home.hero.title3': 'en segundos',
    'home.hero.subtitle': 'Sube una captura. La IA de GlanceFlow extrae tareas, prioridades y plazos automáticamente. Gratis para empezar.',
    'home.hero.cta': 'Empieza gratis — sin tarjeta',
    'home.hero.demo': 'Ver cómo funciona',
    'home.hero.free': '✓ Gratis para siempre',
    'home.hero.noCard': '✓ Sin tarjeta de crédito',
    'home.hero.ai': '✓ Impulsado por IA',
    'home.how.badge': 'Cómo funciona',
    'home.how.title': 'De captura a tareas',
    'home.how.title2': 'en 3 pasos',
    'home.how.step1.title': 'Sube',
    'home.how.step1.desc': 'Haz una captura de cualquier cosa — emails, chats, notas, páginas web.',
    'home.how.step2.title': 'La IA Extrae',
    'home.how.step2.desc': 'Nuestra IA lee la captura y extrae cada tarea, fecha límite y prioridad.',
    'home.how.step3.title': 'Organízate',
    'home.how.step3.desc': 'Las tareas aparecen en tu panel, ordenadas por prioridad y listas para actuar.',
    'home.cta.title': '¿Listo para organizarte?',
    'home.cta.subtitle': 'Únete a miles de usuarios que convirtieron el caos en claridad.',
    'home.cta.btn': 'Empieza gratis',

    'dashboard.title': 'Panel',
    'dashboard.noTasks': 'Sin tareas aún — sube una captura para empezar.',
    'dashboard.upload': 'Subir captura →',
    'dashboard.search': 'Buscar tareas… (/)',
    'dashboard.all': 'Todas',
    'dashboard.pending': 'Pendientes',
    'dashboard.done': 'Hechas',
    'dashboard.task': 'Tarea',
    'dashboard.event': 'Evento',
    'dashboard.reminder': 'Recordatorio',
    'dashboard.markDone': '✓ Marcar como hecho',
    'dashboard.tasks': 'tareas',
    'dashboard.tasksDone': 'hechas',

    'profile.title': 'Perfil',
    'profile.email': 'Correo',
    'profile.plan': 'Plan',
    'profile.plan.free': 'Gratis',
    'profile.plan.premium': '✦ Premium',
    'profile.plan.pro': '✦ Pro',
    'profile.usage': 'Uso hoy',
    'profile.language': 'Idioma',
    'profile.changePassword': 'Cambiar contraseña',
    'profile.changePassword.desc': 'Te enviaremos un enlace de restablecimiento.',
    'profile.changePassword.btn': 'Enviar enlace',
    'profile.changePassword.sent': '¡Correo enviado! Revisa tu bandeja.',
    'profile.member': 'Miembro desde',
    'profile.upgrade': 'Actualizar a Premium →',
    'profile.manageSubscription': 'Gestionar suscripción →',

    'footer.product': 'Producto',
    'footer.legal': 'Legal',
    'footer.terms': 'Términos de Servicio',
    'footer.contact': 'Contacto',
    'footer.rights': '© 2026 GlanceFlow. Todos los derechos reservados.',
    'footer.made': 'Hecho con ♥ para la productividad',
  },

  fr: {
    'nav.home': 'Accueil',
    'nav.dashboard': 'Tableau de bord',
    'nav.pricing': 'Tarifs',
    'nav.profile': 'Profil',
    'nav.signout': 'Se déconnecter',
    'nav.signin': 'Se connecter',
    'nav.tools': 'Outils',
    'nav.upgrade': '+ Améliorer',

    'login.welcome': 'Content de vous revoir',
    'login.create': 'Créer votre compte',
    'login.subtitle.login': 'Connectez-vous à GlanceFlow',
    'login.subtitle.signup': 'Gratuit — 3 tâches par jour',
    'login.google': 'Continuer avec Google',
    'login.google.loading': 'Redirection…',
    'login.or': 'ou',
    'login.email': 'Email',
    'login.password': 'Mot de passe',
    'login.password.placeholder': 'Min 6 caractères',
    'login.submit.login': 'Se connecter',
    'login.submit.signup': 'Créer un compte',
    'login.loading': 'Chargement…',
    'login.noAccount': 'Pas de compte ?',
    'login.hasAccount': 'Déjà un compte ?',
    'login.signupFree': "S'inscrire gratuitement",
    'login.check.title': 'Vérifiez votre email',
    'login.check.desc': 'Nous avons envoyé un lien de confirmation à',
    'login.check.back': 'Retour à la connexion',

    'pricing.badge': 'Tarifs simples',
    'pricing.title': 'Choisissez votre',
    'pricing.title.highlight': 'forfait',
    'pricing.subtitle': 'Commencez gratuitement, passez à un forfait supérieur si nécessaire. Sans frais cachés.',
    'pricing.free.label': 'Gratuit',
    'pricing.free.price': '€0',
    'pricing.free.period': '/toujours',
    'pricing.free.tagline': 'Parfait pour commencer',
    'pricing.free.cta': 'Commencer gratuitement',
    'pricing.premium.label': 'Premium',
    'pricing.premium.price': '€6,99',
    'pricing.premium.period': '/mois',
    'pricing.premium.tagline': 'Pour les utilisateurs quotidiens',
    'pricing.premium.cta': 'Démarrer Premium',
    'pricing.premium.cta.loading': 'Redirection…',
    'pricing.pro.label': 'Pro',
    'pricing.pro.badge': '✦ Le Plus Puissant',
    'pricing.pro.price': '€20',
    'pricing.pro.period': '/mois',
    'pricing.pro.tagline': 'Toute la puissance, sans limites',
    'pricing.pro.cta': 'Démarrer Pro',
    'pricing.pro.cta.loading': 'Redirection…',
    'pricing.unlock.title': 'Ce que vous débloquez avec Pro',
    'pricing.unlock.subtitle': 'Tout ce que Premium offre, plus les outils pour les utilisateurs sérieux',
    'pricing.trust.stripe': '🔒 Sécurisé via Stripe',
    'pricing.trust.cancel': '↩ Annulez à tout moment',
    'pricing.trust.instant': '⚡ Activation instantanée',
    'pricing.trust.vat': '🇪🇺 TVA incluse',
    'pricing.faq.title': 'FAQ',
    'pricing.faq.q1': 'Puis-je annuler à tout moment ?',
    'pricing.faq.a1': 'Oui, annulez en un clic depuis votre portail de facturation Stripe. Sans questions.',
    'pricing.faq.q2': 'Quelle est la différence entre Premium et Pro ?',
    'pricing.faq.a2': 'Premium couvre les captures illimitées et toutes les fonctions IA. Pro ajoute les webhooks, la vue calendrier, le traitement IA prioritaire, les résumés à la demande et les analyses avancées.',
    'pricing.faq.q3': "Qu'est-ce qui compte comme capture d'écran ?",
    'pricing.faq.a3': "Chaque image que vous téléchargez et traitez avec l'IA compte comme une capture.",
    'pricing.faq.q4': 'Les captures gratuites non utilisées sont-elles reportées ?',
    'pricing.faq.a4': 'Non, la limite gratuite se réinitialise chaque jour à minuit.',
    'pricing.faq.q5': "Qu'est-ce que l'AI Smart Summary ?",
    'pricing.faq.a5': "Un email généré par IA qui résume vos tâches en attente, met en évidence les priorités et vous donne un aperçu motivant.",
    'pricing.faq.q6': 'Mes données sont-elles en sécurité ?',
    'pricing.faq.a6': 'Oui. Les tâches sont stockées dans votre base de données Supabase privée. Les captures ne sont jamais sauvegardées.',

    'home.badge': 'Productivité par IA',
    'home.hero.title1': 'Transformez toute capture en',
    'home.hero.title2': 'tâches organisées',
    'home.hero.title3': 'en secondes',
    'home.hero.subtitle': "Téléchargez une capture. L'IA de GlanceFlow extrait automatiquement les tâches, priorités et délais. Gratuit pour commencer.",
    'home.hero.cta': 'Commencer gratuitement — sans carte',
    'home.hero.demo': 'Voir comment ça marche',
    'home.hero.free': '✓ Gratuit pour toujours',
    'home.hero.noCard': '✓ Sans carte de crédit',
    'home.hero.ai': '✓ Propulsé par IA',
    'home.how.badge': 'Comment ça marche',
    'home.how.title': 'De la capture aux tâches',
    'home.how.title2': 'en 3 étapes',
    'home.how.step1.title': 'Téléchargez',
    'home.how.step1.desc': 'Prenez une capture de n\'importe quoi — emails, chats, notes, pages web.',
    'home.how.step2.title': "L'IA Extrait",
    'home.how.step2.desc': "Notre IA lit la capture et extrait chaque tâche, délai et priorité.",
    'home.how.step3.title': 'Organisez-vous',
    'home.how.step3.desc': 'Les tâches apparaissent dans votre tableau de bord, triées par priorité et prêtes à être traitées.',
    'home.cta.title': 'Prêt à vous organiser ?',
    'home.cta.subtitle': "Rejoignez des milliers d'utilisateurs qui ont transformé le chaos en clarté.",
    'home.cta.btn': 'Commencer gratuitement',

    'dashboard.title': 'Tableau de bord',
    'dashboard.noTasks': "Pas encore de tâches — importez une capture d'écran.",
    'dashboard.upload': "Importer une capture →",
    'dashboard.search': 'Rechercher… (/)',
    'dashboard.all': 'Toutes',
    'dashboard.pending': 'En cours',
    'dashboard.done': 'Terminées',
    'dashboard.task': 'Tâche',
    'dashboard.event': 'Événement',
    'dashboard.reminder': 'Rappel',
    'dashboard.markDone': '✓ Marquer comme fait',
    'dashboard.tasks': 'tâches',
    'dashboard.tasksDone': 'terminées',

    'profile.title': 'Profil',
    'profile.email': 'Email',
    'profile.plan': 'Forfait',
    'profile.plan.free': 'Gratuit',
    'profile.plan.premium': '✦ Premium',
    'profile.plan.pro': '✦ Pro',
    'profile.usage': "Utilisation aujourd'hui",
    'profile.language': 'Langue',
    'profile.changePassword': 'Changer le mot de passe',
    'profile.changePassword.desc': 'Nous enverrons un lien de réinitialisation à votre email.',
    'profile.changePassword.btn': 'Envoyer le lien',
    'profile.changePassword.sent': 'Email envoyé ! Vérifiez votre boîte.',
    'profile.member': 'Membre depuis',
    'profile.upgrade': 'Passer à Premium →',
    'profile.manageSubscription': "Gérer l'abonnement →",

    'footer.product': 'Produit',
    'footer.legal': 'Légal',
    'footer.terms': 'Conditions d\'utilisation',
    'footer.contact': 'Contact',
    'footer.rights': '© 2026 GlanceFlow. Tous droits réservés.',
    'footer.made': 'Fait avec ♥ pour la productivité',
  },

  de: {
    'nav.home': 'Start',
    'nav.dashboard': 'Dashboard',
    'nav.pricing': 'Preise',
    'nav.profile': 'Profil',
    'nav.signout': 'Abmelden',
    'nav.signin': 'Anmelden',
    'nav.tools': 'Tools',
    'nav.upgrade': '+ Upgrade',

    'login.welcome': 'Willkommen zurück',
    'login.create': 'Konto erstellen',
    'login.subtitle.login': 'Bei GlanceFlow anmelden',
    'login.subtitle.signup': 'Kostenlos — 3 Aufgaben/Tag',
    'login.google': 'Mit Google fortfahren',
    'login.google.loading': 'Weiterleitung…',
    'login.or': 'oder',
    'login.email': 'E-Mail',
    'login.password': 'Passwort',
    'login.password.placeholder': 'Min. 6 Zeichen',
    'login.submit.login': 'Anmelden',
    'login.submit.signup': 'Konto erstellen',
    'login.loading': 'Laden…',
    'login.noAccount': 'Noch kein Konto?',
    'login.hasAccount': 'Bereits ein Konto?',
    'login.signupFree': 'Kostenlos registrieren',
    'login.check.title': 'E-Mail prüfen',
    'login.check.desc': 'Wir haben einen Bestätigungslink gesendet an',
    'login.check.back': 'Zurück zur Anmeldung',

    'pricing.badge': 'Einfache Preise',
    'pricing.title': 'Wählen Sie Ihren',
    'pricing.title.highlight': 'Plan',
    'pricing.subtitle': 'Kostenlos starten, upgraden wenn nötig. Keine versteckten Kosten.',
    'pricing.free.label': 'Kostenlos',
    'pricing.free.price': '€0',
    'pricing.free.period': '/für immer',
    'pricing.free.tagline': 'Perfekt zum Starten',
    'pricing.free.cta': 'Kostenlos starten',
    'pricing.premium.label': 'Premium',
    'pricing.premium.price': '€6,99',
    'pricing.premium.period': '/Monat',
    'pricing.premium.tagline': 'Für tägliche Power-User',
    'pricing.premium.cta': 'Premium starten',
    'pricing.premium.cta.loading': 'Weiterleitung…',
    'pricing.pro.label': 'Pro',
    'pricing.pro.badge': '✦ Leistungsstärkste',
    'pricing.pro.price': '€20',
    'pricing.pro.period': '/Monat',
    'pricing.pro.tagline': 'Volle Power, keine Limits',
    'pricing.pro.cta': 'Pro starten',
    'pricing.pro.cta.loading': 'Weiterleitung…',
    'pricing.unlock.title': 'Was Sie mit Pro freischalten',
    'pricing.unlock.subtitle': 'Alles von Premium, plus Tools für ernsthafte Nutzer',
    'pricing.trust.stripe': '🔒 Sicher über Stripe',
    'pricing.trust.cancel': '↩ Jederzeit kündbar',
    'pricing.trust.instant': '⚡ Sofortige Aktivierung',
    'pricing.trust.vat': '🇪🇺 MwSt. inklusive',
    'pricing.faq.title': 'FAQ',
    'pricing.faq.q1': 'Kann ich jederzeit kündigen?',
    'pricing.faq.a1': 'Ja, kündigen Sie mit einem Klick über das Stripe-Abrechnungsportal. Keine Fragen.',
    'pricing.faq.q2': 'Was ist der Unterschied zwischen Premium und Pro?',
    'pricing.faq.a2': 'Premium umfasst unbegrenzte Screenshots und alle KI-Funktionen. Pro fügt Webhooks, Kalenderansicht, priorisierte KI-Verarbeitung, On-Demand-Zusammenfassungen und erweiterte Analysen hinzu.',
    'pricing.faq.q3': 'Was zählt als Screenshot?',
    'pricing.faq.a3': 'Jedes Bild, das Sie hochladen und mit KI verarbeiten, zählt als ein Screenshot.',
    'pricing.faq.q4': 'Werden ungenutzte kostenlose Screenshots übertragen?',
    'pricing.faq.a4': 'Nein, das kostenlose Limit wird jeden Tag um Mitternacht zurückgesetzt.',
    'pricing.faq.q5': 'Was ist die AI Smart Summary?',
    'pricing.faq.a5': 'Eine KI-generierte E-Mail, die Ihre ausstehenden Aufgaben zusammenfasst, Prioritäten hervorhebt und Ihnen einen motivierenden Überblick gibt.',
    'pricing.faq.q6': 'Sind meine Daten sicher?',
    'pricing.faq.a6': 'Ja. Aufgaben werden in Ihrer privaten Supabase-Datenbank gespeichert. Screenshots werden nie gespeichert.',

    'home.badge': 'KI-gestützte Produktivität',
    'home.hero.title1': 'Verwandeln Sie jeden Screenshot in',
    'home.hero.title2': 'organisierte Aufgaben',
    'home.hero.title3': 'in Sekunden',
    'home.hero.subtitle': 'Screenshot hochladen. GlanceFlows KI extrahiert automatisch Aufgaben, Prioritäten und Fristen. Kostenlos starten.',
    'home.hero.cta': 'Kostenlos starten — keine Karte',
    'home.hero.demo': 'So funktioniert es',
    'home.hero.free': '✓ Für immer kostenlos',
    'home.hero.noCard': '✓ Keine Kreditkarte',
    'home.hero.ai': '✓ KI-gestützt',
    'home.how.badge': 'So funktioniert es',
    'home.how.title': 'Vom Screenshot zu Aufgaben',
    'home.how.title2': 'in 3 Schritten',
    'home.how.step1.title': 'Hochladen',
    'home.how.step1.desc': 'Machen Sie einen Screenshot von allem — E-Mails, Chats, Notizen, Webseiten.',
    'home.how.step2.title': 'KI Extrahiert',
    'home.how.step2.desc': 'Unsere KI liest den Screenshot und extrahiert jede Aufgabe, Frist und Priorität.',
    'home.how.step3.title': 'Organisiert sein',
    'home.how.step3.desc': 'Aufgaben erscheinen in Ihrem Dashboard, nach Priorität sortiert und bereit zum Handeln.',
    'home.cta.title': 'Bereit, sich zu organisieren?',
    'home.cta.subtitle': 'Schließen Sie sich Tausenden von Nutzern an, die Chaos in Klarheit verwandelt haben.',
    'home.cta.btn': 'Kostenlos starten',

    'dashboard.title': 'Dashboard',
    'dashboard.noTasks': 'Noch keine Aufgaben — lade einen Screenshot hoch.',
    'dashboard.upload': 'Screenshot hochladen →',
    'dashboard.search': 'Aufgaben suchen… (/)',
    'dashboard.all': 'Alle',
    'dashboard.pending': 'Ausstehend',
    'dashboard.done': 'Erledigt',
    'dashboard.task': 'Aufgabe',
    'dashboard.event': 'Ereignis',
    'dashboard.reminder': 'Erinnerung',
    'dashboard.markDone': '✓ Als erledigt markieren',
    'dashboard.tasks': 'Aufgaben',
    'dashboard.tasksDone': 'erledigt',

    'profile.title': 'Profil',
    'profile.email': 'E-Mail',
    'profile.plan': 'Plan',
    'profile.plan.free': 'Kostenlos',
    'profile.plan.premium': '✦ Premium',
    'profile.plan.pro': '✦ Pro',
    'profile.usage': 'Nutzung heute',
    'profile.language': 'Sprache',
    'profile.changePassword': 'Passwort ändern',
    'profile.changePassword.desc': 'Wir senden einen Reset-Link an Ihre E-Mail.',
    'profile.changePassword.btn': 'Link senden',
    'profile.changePassword.sent': 'E-Mail gesendet! Prüfen Sie Ihr Postfach.',
    'profile.member': 'Mitglied seit',
    'profile.upgrade': 'Auf Premium upgraden →',
    'profile.manageSubscription': 'Abonnement verwalten →',

    'footer.product': 'Produkt',
    'footer.legal': 'Rechtliches',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.contact': 'Kontakt',
    'footer.rights': '© 2026 GlanceFlow. Alle Rechte vorbehalten.',
    'footer.made': 'Mit ♥ für Produktivität gemacht',
  },
}

const VALID_LANGS: Lang[] = ['en', 'it', 'es', 'fr', 'de']

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'en',
  setLang: () => null,
  t: (k) => k,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en')

  useEffect(() => {
    const saved = localStorage.getItem('lang') as Lang | null
    if (saved && VALID_LANGS.includes(saved)) setLangState(saved)
  }, [])

  function setLang(l: Lang) {
    setLangState(l)
    localStorage.setItem('lang', l)
  }

  function t(key: string): string {
    return translations[lang][key] ?? translations['en'][key] ?? key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang() {
  return useContext(LanguageContext)
}
